from snakemake.utils import min_version

min_version("7.25.0")


localrules:
    all,


include: "rules/common.smk"


module reads_workflow:
    snakefile:
        github("xsitarcik/reads", path="workflow/Snakefile", tag="v2.0.1")
    config:
        config


use rule * from reads_workflow as reads_*


include: "rules/mapping.smk"


rule all:
    input:
        **reads_workflow.get_outputs(),
        **get_outputs(),
    default_target: True
