from snakemake.utils import min_version

min_version("7.25.0")


localrules:
    all,


include: "rules/common.smk"


reads_config = config.copy()
reads_config.pop("mapping")


module reads_workflow:
    snakefile:
        github("xsitarcik/reads", path="workflow/Snakefile", tag="v1.1.0")
    config:
        reads_config


use rule * from reads_workflow as reads_*


include: "rules/mapping.smk"


rule all:
    input:
        **reads_workflow.get_outputs(),
        **get_outputs(),
    default_target: True
