"$schema": https://json-schema.org/draft/2020-12/schema
"$ref": "#/definitions/MappingWorkflow"
definitions:
  MappingWorkflow:
    type: object
    additionalProperties: true
    properties:
      mapping:
        type: object
        "$ref": "#/definitions/Mapping"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs."
        default: 8
        minimum: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job."
        minimum: 2048
        default: 16384
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
      module_versions:
        type: object
        "$ref": "#/definitions/ModuleVersions"
    required:
      - max_threads
      - max_mem_mb
      - mapping
      - resources
      - threads
      - module_versions
    title: MappingWorkflow
    allOf:
      - if:
          properties:
            mapping:
              properties:
                deduplication:
                  type: string
        then:
          properties:
            resources:
              required:
                - mapping__deduplication_mem_mb
      - if:
          properties:
            mapping:
              properties:
                _generate_qualimap:
                  const: True
        then:
          properties:
            resources:
              required:
                - mapping__qualimap_mem_mb
  Mapping:
    additionalProperties: false
    title: Mapping
    properties:
      mapping:
        type: string
        enum:
          - "bwa"
        description: "Mapping tool to use."
        default: "bwa"
      reference_fasta_paths:
        type: array
        items:
          type: string
        minItems: 1
        default: ["example.fa"]
        description: "References to map against. Provide paths to the reference fasta files."
      deduplication:
        type: [string, "null"]
        description: "Deduplication method to use."
        enum:
          - "picard"
          - null
        default: null
        examples:
          - "picard"
      _generate_qualimap:
        type: boolean
        description: "If true, qualimap is generated for the last bam step (deduplication or original)."
        examples: [true]
    required:
      - mapping
      - reference_fasta_paths
      - deduplication
      - _generate_qualimap
  Resources:
    additionalProperties: true
    properties:
      mapping__mapping_mem_mb:
        type: integer
        description: "Memory in MB to reserve for mapping"
        default: 8192
      mapping__indexing_mem_mb:
        type: integer
        description: "Memory in MB to reserve for bam_index"
        default: 4096
      mapping__deduplication_mem_mb:
        type: integer
        description: "Memory in MB to reserve for picard"
        default: 8192
      mapping__qualimap_mem_mb:
        type: integer
        description: "Memory in MB to reserve for qualimap"
        default: 4096
    required:
      - mapping__mapping_mem_mb
      - mapping__indexing_mem_mb
    title: Resources
  Threads:
    additionalProperties: true
    properties:
      mapping__mapping:
        type: integer
        default: 4
        minimum: 1
        description: "Number of threads to use for mapping"
      mapping__indexing:
        type: integer
        default: 2
        minimum: 1
        description: "Number of threads to use for bam_index"
    title: Threads
    required:
      - mapping__mapping
      - mapping__indexing
  ModuleVersions:
    type: object
    additionalProperties: true
    properties:
      reads:
        type: string
        default: "v3.4.4"
        pattern: "v[0-9]+.[0-9]+.[0-9]+"
        description: "Version of reads module"
    title: ModuleVersions
    required:
      - reads
